---
- name: Update cache in all hosts
  hosts: all
  become: true
  tasks:
    - name: Update Cache
      apt:
        update_cache: yes

- name: Configure Web Servers
  hosts: webservers
  become: true
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Requirements
      apt:
        name: python3-pip
        state: latest
        update_cache: true

    - name: Installing Flask
      pip:
        executable: pip3
        name: flask
        state: latest

    - name: Install Flask Service Deployment
      apt:
        name: gunicorn

    - name: Copy app
      copy:
        src: app.py
        dest: /home/ubuntu/app1.py
        owner: ubuntu
        mode: '0644'

    - name: Deploying Flask Webservers
      shell: gunicorn -w 2 -D -b 0.0.0.0:8000 app1:app

- name: Install HAProxy and Configure
  hosts: HAproxy
  become: true
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Installing HAProxy
      package:
        name: haproxy
        state: present

    - name: Copy HAProxy cfg file
      template:
        src: haproxy.cfg.j2
        dest: /etc/haproxy/haproxy.cfg

    - name: Restarting HAProxy service
      service:
        name: haproxy
        state: restarted
